### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by omegaeducacional** [digitalocean/doctl#1390]
**Problem with doctl registry repository**

When i run this command i get a title message

```bash
doctl registry repository list-v2 --access-token=dop_*********
``` 

**Environment:**

 - doctl version: doctl version 1.97.0-release
Git commit hash: 0e49bd7a

 - OS: UBUNTU 22.04
 - Installation method: Snap

**Additional Details:**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0xa1b174]

goroutine 1 [running]:
github.com/digitalocean/doctl/commands/displayers.(*RepositoryV2).KV(0xc000863080)
	github.com/digitalocean/doctl/commands/displayers/registry.go:147 +0xb4
github.com/digitalocean/doctl/commands/displayers.DisplayText({0x1299f18, 0xc000863080}, {0x128f240, 0xc00012e008}, 0x0, {0x0, 0x0, 0xc00099fb50?})
	github.com/digitalocean/doctl/commands/displayers/output.go:91 +0x2eb
github.com/digitalocean/doctl/commands/displayers.(*Displayer).Display(0xc00099fbb8)
	github.com/digitalocean/doctl/commands/displayers/output.go:61 +0x18d
github.com/digitalocean/doctl/commands.(*CmdConfig).Display(0xc0000071e0, {0x1299f18?, 0xc000863080?})
	github.com/digitalocean/doctl/commands/command_config.go:226 +0x135
github.com/digitalocean/doctl/commands.displayRepositoriesV2(...)
	github.com/digitalocean/doctl/commands/registry.go:758
github.com/digitalocean/doctl/commands.RunListRepositoriesV2(0xc0000071e0)
	github.com/digitalocean/doctl/commands/registry.go:623 +0x119
github.com/digitalocean/doctl/commands.cmdBuilderWithInit.func1(0xc000241800?, {0xc000278eb0, 0x0, 0x1})
	github.com/digitalocean/doctl/commands/command.go:85 +0xe4
github.com/spf13/cobra.(*Command).execute(0xc000241800, {0xc000278e90, 0x1, 0x1})
	github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x19995a0)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/digitalocean/doctl/commands.Execute()
	github.com/digitalocean/doctl/commands/doit.go:145 +0x27
main.main()
	./main.go:24 +0x31
```

**Comment by bentranter** [comment]
Thanks for the report @omegaeducacional, I've just opened a PR to fix this.

**Comment by bentranter** [comment]
This is fixed in [v1.97.1](https://github.com/digitalocean/doctl/releases/tag/v1.97.1).
