### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by clemenko** [digitalocean/doctl#149]
On OSX 10.12 (Sierra) I get will run doctl command and get an error. Then I run it again and it works. 

```
clemenko13:Desktop clemenko$ doctl compute droplet list
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0xc5dc0]

goroutine 1 [running]:
runtime.throw(0x7dcd80, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc820151158 sp=0xc820151140
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc8201511a8 sp=0xc820151158
sync.(*Pool).Get(0xa56cd0, 0x0, 0x0)
	/usr/local/go/src/sync/pool.go:102 +0x40 fp=0xc8201511f8 sp=0xc8201511a8
fmt.newPrinter(0xe44080)
	/usr/local/go/src/fmt/print.go:133 +0x27 fp=0xc820151238 sp=0xc8201511f8
fmt.Sprintln(0xc820151448, 0x2, 0x2, 0x0, 0x0)
	/usr/local/go/src/fmt/print.go:270 +0x28 fp=0xc820151288 sp=0xc820151238
log.(*Logger).Println(0xc820080d20, 0xc820151448, 0x2, 0x2)
	/usr/local/go/src/log/log.go:182 +0x35 fp=0xc8201512d0 sp=0xc820151288
github.com/digitalocean/doctl/vendor/github.com/spf13/cast.ToStringE(0x536840, 0xc8201b6500, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/digitalocean/doctl/vendor/github.com/spf13/cast/caste.go:192 +0x27c fp=0xc820151470 sp=0xc8201512d0
github.com/digitalocean/doctl/vendor/github.com/spf13/cast.ToString(0x536840, 0xc8201b6500, 0x0, 0x0)
	/go/src/github.com/digitalocean/doctl/vendor/github.com/spf13/cast/cast.go:36 +0x37 fp=0xc8201514a8 sp=0xc820151470
github.com/digitalocean/doctl/vendor/github.com/spf13/viper.(*Viper).Get(0xc8201340e0, 0x70fc88, 0x6, 0x0, 0x0)
	/go/src/github.com/digitalocean/doctl/vendor/github.com/spf13/viper/viper.go:509 +0xb83 fp=0xc8201516b8 sp=0xc8201514a8
github.com/digitalocean/doctl/vendor/github.com/spf13/viper.(*Viper).GetString(0xc8201340e0, 0x70fc88, 0x6, 0x0, 0x0)
	/go/src/github.com/digitalocean/doctl/vendor/github.com/spf13/viper/viper.go:540 +0x41 fp=0xc8201516f8 sp=0xc8201516b8
github.com/digitalocean/doctl/vendor/github.com/spf13/viper.GetString(0x70fc88, 0x6, 0x0, 0x0)
	/go/src/github.com/digitalocean/doctl/vendor/github.com/spf13/viper/viper.go:538 +0x43 fp=0xc820151728 sp=0xc8201516f8
github.com/digitalocean/doctl.(*LiveConfig).GetString(0xc82007c028, 0x70d3e0, 0x5, 0x70fc88, 0x6, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/digitalocean/doctl/doit.go:232 +0xb0 fp=0xc820151820 sp=0xc820151728
github.com/digitalocean/doctl/commands.(*displayer).Display(0xc8201518f0, 0x0, 0x0)
	/go/src/github.com/digitalocean/doctl/commands/commands.go:42 +0x73 fp=0xc8201518d8 sp=0xc820151820
github.com/digitalocean/doctl/commands.(*CmdConfig).Display(0xc8201ba4e0, 0xe00458, 0xc8203ca8c0, 0x0, 0x0)
	/go/src/github.com/digitalocean/doctl/commands/doit.go:356 +0xb7 fp=0xc820151938 sp=0xc8201518d8
github.com/digitalocean/doctl/commands.RunDropletList(0xc8201ba4e0, 0x0, 0x0)
	/go/src/github.com/digitalocean/doctl/commands/droplets.go:592 +0x77a fp=0xc820151b78 sp=0xc820151938
github.com/digitalocean/doctl/commands.cmdBuilderWithInit.func1(0xc820188800, 0xa80b70, 0x0, 0x0)
	/go/src/github.com/digitalocean/doctl/commands/doit.go:379 +0x1ae fp=0xc820151c58 sp=0xc820151b78
github.com/digitalocean/doctl/vendor/github.com/spf13/cobra.(*Command).execute(0xc820188800, 0xa80b70, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/digitalocean/doctl/vendor/github.com/spf13/cobra/command.go:565 +0x85a fp=0xc820151d70 sp=0xc820151c58
github.com/digitalocean/doctl/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xa5d580, 0xc820188800, 0x0, 0x0)
	/go/src/github.com/digitalocean/doctl/vendor/github.com/spf13/cobra/command.go:651 +0x55c fp=0xc820151e80 sp=0xc820151d70
github.com/digitalocean/doctl/vendor/github.com/spf13/cobra.(*Command).Execute(0xa5d580, 0x0, 0x0)
	/go/src/github.com/digitalocean/doctl/vendor/github.com/spf13/cobra/command.go:610 +0x2d fp=0xc820151ea8 sp=0xc820151e80
github.com/digitalocean/doctl/commands.Execute()
	/go/src/github.com/digitalocean/doctl/commands/doit.go:137 +0x2a fp=0xc820151f28 sp=0xc820151ea8
main.main()
	/go/src/github.com/digitalocean/doctl/cmd/doctl/main.go:24 +0x31 fp=0xc820151f40 sp=0xc820151f28
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc820151f90 sp=0xc820151f40
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820151f98 sp=0xc820151f90

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1
clemenko13:Desktop clemenko$ doctl compute droplet list
ID		Name		Public IPv4	Public IPv6	Memory	VCPUs	Disk	Region	Image		Status	Tags
27993913	core-test	192.241.169.120			2048	2	40	nyc2	CentOS 7.2 x64	active	
```

**Comment by bryanl** [comment]
Hello, this is a go/Sierra issue. We will be issuing a version compiled with go 1.7.1 by tomorrow.

**Comment by clemenko** [comment]
Cool!

**Comment by bryanl** [comment]
There is a new release out that should fix this issue.
