### ISSUE TITLE
`doctl apps logs ${ID}` panics (until logs become available)

### ISSUE THREAD

**Issue by DazWilkin** [digitalocean/doctl#878]
**Describe the Issue:**

I'm a fan of `doctl` and decided to start using it from the get-go as I explore `doctl apps`. I deployed  a `Dockerfile `based app and noticed that, before the deployment completed (and before logs became available), `doctl apps  logs ${ID}` panics. Once logs become available, the command succeeds.

**Environment:**

 - doctl version:
```
doctl version 1.48.0-release
Git commit hash: 03410cbf
```
 - OS:  Linux
```
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

 - Installation method: Snap

**Additional Details:**

```bash
doctl apps logs ${ID}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xd1da34]

goroutine 1 [running]:
github.com/digitalocean/doctl/commands.RunAppsGetLogs(0xc000416000, 0x0, 0x0)
	/build/parts/doctl/build/commands/apps.go:360 +0x7e4
github.com/digitalocean/doctl/commands.cmdBuilderWithInit.func1(0xc0002ab900, 0xc000384450, 0x1, 0x1)
	/build/parts/doctl/build/commands/command.go:69 +0x146
github.com/spf13/cobra.(*Command).execute(0xc0002ab900, 0xc000384410, 0x1, 0x1, 0xc0002ab900, 0xc000384410)
	/build/parts/doctl/build/vendor/github.com/spf13/cobra/command.go:766 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x17ae5a0, 0xc00032fcc0, 0xc00000e020, 0xc00016df48)
	/build/parts/doctl/build/vendor/github.com/spf13/cobra/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/build/parts/doctl/build/vendor/github.com/spf13/cobra/command.go:800
github.com/digitalocean/doctl/commands.Execute()
	/build/parts/doctl/build/commands/doit.go:125 +0x34
main.main()
	/build/parts/doctl/build/cmd/doctl/main.go:24 +0x47
```
Once deployment completes:

```bash
doctl apps logs ${ID}
do-apps-rust 2020-10-08T18:22:02.033405233Z Configured for staging.
do-apps-rust 2020-10-08T18:22:02.033464332Z     => address: 0.0.0.0
do-apps-rust 2020-10-08T18:22:02.033471253Z     => port: 8080
do-apps-rust 2020-10-08T18:22:02.033518060Z     => log: normal
do-apps-rust 2020-10-08T18:22:02.033552204Z     => workers: 16
do-apps-rust 2020-10-08T18:22:02.033559504Z     => secret key: generated
do-apps-rust 2020-10-08T18:22:02.033566840Z     => limits: forms = 32KiB
do-apps-rust 2020-10-08T18:22:02.033591067Z     => keep-alive: 5s
do-apps-rust 2020-10-08T18:22:02.033606471Z     => tls: disabled
do-apps-rust 2020-10-08T18:22:02.033616208Z Mounting /metrics:
do-apps-rust 2020-10-08T18:22:02.033740130Z     => GET /metrics
do-apps-rust 2020-10-08T18:22:02.033766154Z Mounting /:
do-apps-rust 2020-10-08T18:22:02.033777116Z     => GET /cached (cached)
do-apps-rust 2020-10-08T18:22:02.033831492Z     => GET / (default)
do-apps-rust 2020-10-08T18:22:02.033876916Z     => GET /env (env)
do-apps-rust 2020-10-08T18:22:02.033906050Z     => GET /headers (headers)
do-apps-rust 2020-10-08T18:22:02.034023910Z     => GET /hello/<name>/<age> (hello)
do-apps-rust 2020-10-08T18:22:02.034041051Z Fairings:
do-apps-rust 2020-10-08T18:22:02.034056161Z     => 1 request: Prometheus metric collection
do-apps-rust 2020-10-08T18:22:02.034098131Z     => 1 response: Prometheus metric collection
do-apps-rust 2020-10-08T18:22:02.034579733Z Rocket has launched from http://0.0.0.0:8080
do-apps-rust 2020-10-08T18:22:26.127791284Z GET / text/html:
do-apps-rust 2020-10-08T18:22:26.127833016Z     => Matched: GET / (default)
do-apps-rust 2020-10-08T18:22:26.127848528Z     => Outcome: Success
do-apps-rust 2020-10-08T18:22:26.130307679Z     => Response succeeded.
do-apps-rust 2020-10-08T18:22:26.717554064Z GET /favicon.ico image/avif:
do-apps-rust 2020-10-08T18:22:26.717597612Z     => Error: No matching routes for GET /favicon.ico image/avif.
do-apps-rust 2020-10-08T18:22:26.717689738Z     => Warning: Responding with 404 Not Found catcher.
do-apps-rust 2020-10-08T18:22:26.717841224Z     => Response succeeded.
do-apps-rust 2020-10-08T18:22:30.989811691Z GET /headers text/html:
do-apps-rust 2020-10-08T18:22:30.989883913Z     => Matched: GET /headers (headers)
do-apps-rust 2020-10-08T18:22:30.989900614Z     => Outcome: Success
do-apps-rust 2020-10-08T18:22:30.990143753Z     => Response succeeded.
```

**Comment by andrewsomething** [comment]
Thanks for flagging this for us @DazWilkin! 

Looks like we need to protect against there not being an `ActiveDeployment` yet:

https://github.com/digitalocean/doctl/blob/9c5be03f65c33b6717bc6525923d1cfc992632b9/commands/apps.go#L360

**Comment by andrewsomething** [comment]
Just made a v1.48.1 bug fix release with this change. Thanks again for reporting the issue!
