### ISSUE TITLE
`doctl auth init` not working on Windows 10 powershell

### ISSUE THREAD

**Issue by JohnathanWeisner** [digitalocean/doctl#908]
**Describe the Issue:**

Not able to authorize doctl after installing doctl via the instructions https://www.digitalocean.com/docs/apis-clis/doctl/how-to/install/

After following the instructions in the link above and getting to the step when you must run:
`doctl auth init --context <NAME>`
And supplying a newly created valid API key I'm met with this error:
```
doctl auth init --context batman
Please authenticate doctl for use with your DigitalOcean account. You can generate a token in the control panel at https://cloud.digitalocean.com/account/api/tokens

Enter your access token:
Validating token... invalid token

Error: Unable to use supplied token to access API: Get "https://api.digitalocean.com/v2/account": net/http: invalid header field value "Bearer \x16" for key Authorization
```

**Environment:**

 - doctl version: ```doctl version 1.48.1-release
Git commit hash: a5b1cd2
release 1.49.0 is available, check it out!```
 - OS: Windows 10 Pro Version 1903
 - Installation method: `Invoke-WebRequest https://github.com/digitalocean/doctl/releases/download/v1.48.1/doctl-1.48.1-windows-amd64.zip -OutFile ~\doctl-1.48.1-windows-amd64.zip`

**Additional Details:**

Trace
```
Validating token... doctl: 2020/10/29 21:47:56 -> "GET /v2/account HTTP/1.1\r\nHost: api.digitalocean.com\r\nUser-Agent: doctl/1.48.1-release (windows amd64) godo/1.46.0\r\nAccept: application/json\r\nContent-Type: application/json\r\nAccept-Encoding: gzip\r\n\r\n"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x48 pc=0x86458a]

goroutine 1 [running]:
net/http/httputil.DumpResponse(0x0, 0xc0003db201, 0x0, 0x10e3620, 0xc0003e4650, 0xc7, 0x0)
        /home/travis/.gimme/versions/go1.14.9.linux.amd64/src/net/http/httputil/dump.go:305 +0x4a
github.com/digitalocean/doctl.(*recorder).RoundTrip(0xc000395cc0, 0xc0003db200, 0xc000395cc0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/digitalocean/doctl/recorder.go:47 +0x183
net/http.send(0xc0003db200, 0x10e36e0, 0xc000395cc0, 0x0, 0x0, 0x0, 0xc00028eb38, 0x4, 0x1, 0x0)
        /home/travis/.gimme/versions/go1.14.9.linux.amd64/src/net/http/client.go:252 +0x445
net/http.(*Client).send(0xc0003c9a70, 0xc0003db200, 0x0, 0x0, 0x0, 0xc00028eb38, 0x0, 0x1, 0xf67006)
        /home/travis/.gimme/versions/go1.14.9.linux.amd64/src/net/http/client.go:176 +0x101
net/http.(*Client).do(0xc0003c9a70, 0xc0003db200, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.14.9.linux.amd64/src/net/http/client.go:699 +0x451
net/http.(*Client).Do(...)
        /home/travis/.gimme/versions/go1.14.9.linux.amd64/src/net/http/client.go:567
github.com/digitalocean/godo.DoRequestWithClient(0x10ffb80, 0xc0000300d8, 0xc0003c9a70, 0xc0003db100, 0x0, 0x8, 0x8)
        /home/travis/gopath/src/github.com/digitalocean/doctl/vendor/github.com/digitalocean/godo/godo.go:388 +0xd5
github.com/digitalocean/godo.(*Client).Do(0xc0002ba900, 0x10ffb80, 0xc0000300d8, 0xc0003db100, 0xdd9ce0, 0xc00028eb28, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/digitalocean/doctl/vendor/github.com/digitalocean/godo/godo.go:325 +0xa0
github.com/digitalocean/godo.(*AccountServiceOp).Get(0xc00028ea30, 0x10ffb80, 0xc0000300d8, 0xc00012bc00, 0xd7a92d, 0xe7a0a0, 0xc00028eb20)
        /home/travis/gopath/src/github.com/digitalocean/doctl/vendor/github.com/digitalocean/godo/account.go:54 +0x108
github.com/digitalocean/doctl/do.(*accountService).Get(0xc00028eb20, 0xc00028eb20, 0x0, 0x1)
        /home/travis/gopath/src/github.com/digitalocean/doctl/do/account.go:51 +0x5a
github.com/digitalocean/doctl/commands.RunAuthInit.func1(0xc0003e8000, 0x0, 0x110ce80)
        /home/travis/gopath/src/github.com/digitalocean/doctl/commands/auth.go:138 +0x26f
github.com/digitalocean/doctl/commands.cmdBuilderWithInit.func1(0xc000301400, 0xc0003e4180, 0x0, 0x1)
        /home/travis/gopath/src/github.com/digitalocean/doctl/commands/command.go:69 +0x14d
github.com/spf13/cobra.(*Command).execute(0xc000301400, 0xc0003e4150, 0x1, 0x1, 0xc000301400, 0xc0003e4150)
        /home/travis/gopath/src/github.com/digitalocean/doctl/vendor/github.com/spf13/cobra/command.go:766 +0x2a4
github.com/spf13/cobra.(*Command).ExecuteC(0x17b50a0, 0xc0002ef650, 0xc000006020, 0xc00012bf48)
        /home/travis/gopath/src/github.com/digitalocean/doctl/vendor/github.com/spf13/cobra/command.go:852 +0x2f1
github.com/spf13/cobra.(*Command).Execute(...)
        /home/travis/gopath/src/github.com/digitalocean/doctl/vendor/github.com/spf13/cobra/command.go:800
github.com/digitalocean/doctl/commands.Execute()
        /home/travis/gopath/src/github.com/digitalocean/doctl/commands/doit.go:125 +0x3b
main.main()
        /home/travis/gopath/src/github.com/digitalocean/doctl/cmd/doctl/main.go:24 +0x4e
```
I've deleted the API key from my account just incase this trace gives something away that I'm not aware of.

**Comment by andrewsomething** [comment]
Hi @JohnathanWeisner,

Thanks for reporting this. This error:

`net/http: invalid header field value "Bearer \x16" for key Authorization`

seems to suggest that the token was read as the key combination Ctrl+V rather than the contents of the clipboard. Can you confirm whether or not it works as expected if you paste the password using a different method, i.e. right click?

**Comment by andrewsomething** [comment]
I'm going to go ahead and close this one out. Please feel free to re-open if you can provide details to reproduce this.
